version: '3.7'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "8008:80"
    volumes:
      - ./CaddyFile:/etc/caddy/CaddyFile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
